### ISSUE TITLE
FileExistsError: [Errno 17] File exists: './log/TwoStageNet'

### ISSUE THREAD

**Issue by SSSSamZhu** [ouc-ocean-group/RRNet#11]
Hi, I encountered the following error when using `train.py`.

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/cheny/miniconda3/envs/zgm_RRnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/Sam_zhu/RRnet/operators/distributed_wrapper.py", line 65, in dist_training_process
    operator.training_process()
  File "/mnt/Sam_zhu/RRnet/operators/rrnet_operator.py", line 106, in training_process
    logger = Logger(self.cfg)
  File "/mnt/Sam_zhu/RRnet/utils/vis/logger.py", line 17, in __init__
    self.log_dir = self.create_log_dir(cfg.log_prefix)
  File "/mnt/Sam_zhu/RRnet/utils/vis/logger.py", line 79, in create_log_dir
    os.makedirs(log_dir)
  File "/home/cheny/miniconda3/envs/zgm_RRnet/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: './log/TwoStageNet'
```
After searching, I found that this may be an `OS` bug, it seems that if the '/TwoStageNet' folder has been created, an error will be reported when `os.mkdirs` is executed,so I deleted the `/TwoStageNet` folder. At the same time, some other methods have been adopted to make this error no longer reported. 
But the accompanying problem is that I found that the GPU share is 0. I'm not sure whether this is related, so I reported it together.

![image](https://user-images.githubusercontent.com/100264795/199762052-d54e965d-149d-4680-887b-53f311098fc2.png)

The terminal only prints these two lines of information, and there is no updated message.
```
(XXXX) XX@XX:/XXX$ /XXXX/python /XXXX/train.py
=> Use GPU: 0
=> Use GPU: 1
```
Look forward to your reply.

**Comment by GeoffreyChen777** [comment]
FileExistsError: [Errno 17] File exists: './log/TwoStageNet'

**Comment by GeoffreyChen777** [comment]
What is the GPU share?

**Comment by SSSSamZhu** [comment]
Hi, @GeoffreyChen777 
Sorry, My expression is not clear enough. I mean `Volatile GPU-Util` in the screenshot. The memory display has been loaded into the GPU, but the GPU is not working.

> What is the GPU share?

**Comment by GeoffreyChen777** [comment]
Sorry, can't reproduce your problem...

**Comment by SSSSamZhu** [comment]
Hi, @GeoffreyChen777
I apologize for my bold behavior in relaunching the question. I have the following questions to answer.

1. I want to know what will be printed when the terminal usually runs. My terminal publishes these contents.

```
cheny@server:/home/data2/RRnet 2022-11-21 10:31:26
$ CUDA_VISIBLE_DEVICES=0,1 /home/cheny/miniconda3/envs/zgm/bin/python train.py 
=> Use GPU: 0
=> Use GPU: 1
Training is Done!
```
In addition, the GPU of my computer never works, just like in the screenshot, I posted earlier. 

This is my change in `rrnet_operator.py`, as you see, I tried to print loss without success.
```
        for step in range(self.cfg.Train.iter_num):
            ##print(step)
            self.optimizer.zero_grad()
            
            try:
                imgs, annos, gt_hms, gt_whs, gt_inds, gt_offsets, gt_reg_masks, names = self.training_loader.get_batch()
                targets = gt_hms, gt_whs, gt_inds, gt_offsets, gt_reg_masks, annos
            except RuntimeError as e:
                if 'out of memory' in str(e):
                    print("WARNING: ran out of memory with exception at step {}.".format(step))
                continue

            outs = self.model(imgs)
            targets = gt_hms, gt_whs, gt_inds, gt_offsets, gt_reg_masks, annos
            hm_loss, wh_loss, offset_loss, s2_reg_loss = self.criterion(outs, targets)

            if step < 2000:
                s2_factor = 0
            else:
                s2_factor = 1
            loss = hm_loss + (0.1 * wh_loss) + offset_loss + s2_reg_loss*s2_factor
            print(loss)##
            loss.backward()
            self.optimizer.step()
            self.lr_sch.step()

            total_loss += float(loss)
            total_hm_loss += float(hm_loss)
            total_wh_loss += float(wh_loss)
            total_off_loss += float(offset_loss)
            total_s2_reg_loss += float(s2_reg_loss)
```

2. I once suspected that the parameters of distributed training had not been modified correctly, which caused the GPU to only load memory but not work. How can I modify it `Config.Distributed.dist_url` ? I tried to locate the problem, which may be caused by distributed training.

```
# Distributed Config =========================================
Config.Distributed = edict()
Config.Distributed.world_size = 1
Config.Distributed.gpu_id = -1
Config.Distributed.rank = 0
Config.Distributed.ngpus_per_node = 1
Config.Distributed.dist_url = 'tcp://127.0.1.1:34564'##tcp://127.0.0.1:34564 tcp://172.31.226.16:22
```
Looking forward to your reply.

**Comment by GeoffreyChen777** [comment]
Are you going to train rrnet on a single machine with multiple gpus?

**Comment by SSSSamZhu** [comment]
@GeoffreyChen777  Hi, 
Forgive me for missing your reply. I have a computer with two GPUs. I can also use the command `CUDA_VISIBLE_DEVICES=0` to use one of the GPUs, depending on whether the code works properly.

**Comment by GeoffreyChen777** [comment]
Ummm, weird.

maybe try to print the world size and the local rank first:

```
import torch.distributed as dist
print(dist.get_rank())
print(dist.get_world_size())
```

**Comment by SSSSamZhu** [comment]
Hi @GeoffreyChen777 
I think this result is reasonable, I use a machine with two GPUs. Because this is parallel, the print results are out of order.
```
nnodes = 1
node_rank = 0, 1
world_size = 1*2 = 2
```
Specific print:
```
$ /home/cheny/miniconda3/envs/zgm/bin/python  train.py
=> Use GPU: 0
=> Use GPU: 1
1
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
0
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
0
2
0
2
0
2
0
2
0
2
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
```
Specific modification:
```
for step in range(self.cfg.Train.iter_num):
            
            self.optimizer.zero_grad()
            print(dist.get_rank())######
            print(dist.get_world_size())######
            try:
                imgs, annos, gt_hms, gt_whs, gt_inds, gt_offsets, gt_reg_masks, names = self.training_loader.get_batch()
                targets = gt_hms, gt_whs, gt_inds, gt_offsets, gt_reg_masks, annos
            except RuntimeError as e:
                if 'out of memory' in str(e):
                    print("WARNING: ran out of memory with exception at step {}.".format(step))
                continue

            outs = self.model(imgs)
            targets = gt_hms, gt_whs, gt_inds, gt_offsets, gt_reg_masks, annos
            hm_loss, wh_loss, offset_loss, s2_reg_loss = self.criterion(outs, targets)

            if step < 2000:
                s2_factor = 0
            else:
                s2_factor = 1
            loss = hm_loss + (0.1 * wh_loss) + offset_loss + s2_reg_loss*s2_factor
            print(loss)
            loss.backward()
            self.optimizer.step()
            self.lr_sch.step()

            total_loss += float(loss)
            total_hm_loss += float(hm_loss)
            total_wh_loss += float(wh_loss)
            total_off_loss += float(offset_loss)
            total_s2_reg_loss += float(s2_reg_loss)

            if self.main_proc_flag:
                if step % self.cfg.Train.print_interval == self.cfg.Train.print_interval - 1:
                    # Loss
                    for param_group in self.optimizer.param_groups:
                        lr = param_group['lr']
                    log_data = {'scalar': {
                        'train/total_loss': total_loss / self.cfg.Train.print_interval,
                        'train/hm_loss': total_hm_loss / self.cfg.Train.print_interval,
                        'train/wh_loss': total_wh_loss / self.cfg.Train.print_interval,
                        'train/off_loss': total_off_loss / self.cfg.Train.print_interval,
                        'train/s2_reg_loss': total_s2_reg_loss / self.cfg.Train.print_interval,
                        'train/lr': lr
                    }}
                    print(log_data)

                    # Generate bboxs
                    s1_pred_bbox, s2_pred_bbox = self.generate_bbox(outs, batch_idx=0)

                    # Visualization
                    img = (denormalize(imgs[0].cpu()).permute(1, 2, 0).cpu().numpy() * 255).astype(np.uint8)
                    # Do nms
                    s2_pred_bbox = self._ext_nms(s2_pred_bbox)
                    #
                    s1_pred_on_img = visualize(img.copy(), s1_pred_bbox, xywh=True, with_score=True)
                    s2_pred_on_img = visualize(img.copy(), s2_pred_bbox, xywh=True, with_score=True)
                    gt_img = visualize(img.copy(), annos[0, :, :6], xywh=False)

                    s1_pred_on_img = torch.from_numpy(s1_pred_on_img).permute(2, 0, 1).unsqueeze(0).float() / 255.
                    s2_pred_on_img = torch.from_numpy(s2_pred_on_img).permute(2, 0, 1).unsqueeze(0).float() / 255.
                    gt_on_img = torch.from_numpy(gt_img).permute(2, 0, 1).unsqueeze(0).float() / 255.
                    log_data['imgs'] = {'Train': [s1_pred_on_img, s2_pred_on_img, gt_on_img]}
                    logger.log(log_data, step)

                    total_loss = 0
                    total_hm_loss = 0
                    total_wh_loss = 0
                    total_off_loss = 0
                    total_s2_reg_loss = 0

                if step % self.cfg.Train.checkpoint_interval == self.cfg.Train.checkpoint_interval - 1 or \
                        step == self.cfg.Train.iter_num - 1:
                    self.save_ckp(self.model.module, step, logger.log_dir)

    def generate_bbox(self, outs, batch_idx=0):
        s1_hms, s1_whs, s1_offsets, s2_reg, bxyxy, scores, clses = outs
        batch_flag = bxyxy[:, 0] == batch_idx
        s2_reg = s2_reg[batch_flag]
        xyxy = bxyxy[batch_flag, 1:] * self.cfg.Train.scale_factor
        score = scores[batch_flag]
        clses = clses[batch_flag]

        s1_xywh = xyxy
        s1_xywh[:, 2:4] -= s1_xywh[:, 0:2]
        s1_bboxes = torch.cat((s1_xywh, score.view(-1, 1), torch.zeros((s1_xywh.size(0), 1), device=xyxy.device)), dim=1)

        s2_xywh = s1_xywh
        s2_xywh[:, 2:4] += 1
        out_ctr_x = s2_reg[:, 0] * s2_xywh[:, 2] + s2_xywh[:, 0] + s2_xywh[:, 2] / 2
        out_ctr_y = s2_reg[:, 1] * s2_xywh[:, 3] + s2_xywh[:, 1] + s2_xywh[:, 3] / 2
        out_w = s2_reg[:, 2].exp() * s2_xywh[:, 2]
        out_h = s2_reg[:, 3].exp() * s2_xywh[:, 3]
        out_x = out_ctr_x - out_w / 2.
        out_y = out_ctr_y - out_h / 2.
        s2_bboxes = torch.stack((out_x, out_y, out_w, out_h, score, clses.float()+1), dim=1)
        return s1_bboxes, s2_bboxes

    @staticmethod
    def _ext_nms(pred_bbox, per_cls=True):
        if pred_bbox.size(0) == 0:
            return pred_bbox
        keep_bboxs = []
        if per_cls:
            cls_unique = pred_bbox[:, 5].unique()
            for cls in cls_unique:
                cls_idx = pred_bbox[:, 5] == cls
                bbox_for_nms = pred_bbox[cls_idx].detach().cpu().numpy()
                bbox_for_nms[:, 2] = bbox_for_nms[:, 0] + bbox_for_nms[:, 2]
                bbox_for_nms[:, 3] = bbox_for_nms[:, 1] + bbox_for_nms[:, 3]
                keep_bbox = soft_nms(bbox_for_nms, Nt=0.7, threshold=0.1, method=2)
                keep_bboxs.append(keep_bbox)
            keep_bboxs = np.concatenate(keep_bboxs, axis=0)
        else:
            bbox_for_nms = pred_bbox.detach().cpu().numpy()
            bbox_for_nms[:, 2] = bbox_for_nms[:, 0] + bbox_for_nms[:, 2]
            bbox_for_nms[:, 3] = bbox_for_nms[:, 1] + bbox_for_nms[:, 3]
            keep_bboxs = soft_nms(bbox_for_nms, Nt=0.7, threshold=0.1, method=2)
        keep_bboxs[:, 2:4] -= keep_bboxs[:, 0:2]
        return torch.from_numpy(keep_bboxs)
```

**Comment by SSSSamZhu** [comment]
My problem has been solved. Thank you for your @GeoffreyChen777  help.  Submit a bug in a program：
https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/operators/rrnet_operator.py#L120-L126

If an error occurs between `L121-L122`, and the error is not `out of memory`, it will jump out of this loop and start a new one. No exceptions will be thrown during this process. The overall situation is as I described earlier. Hope it can help developers who use this project in the future.

Finally, add the specific problems I encountered. Most of the problems I encountered were caused by the long distance between the project time and the current one, and the newer version I used.
1. ```RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.```

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/datasets/transforms/functional.py#L311

change to
`anno = data[1][~ ign_idx, :] `

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/datasets/transforms/transforms.py#L78

change to
`            remove_large_flag = ~ (((annos[:, 2] > self.w) + (annos[:, 3] > self.h)) > 0)`

2. ```TypeError: Argument 'flags' must be integer, not bool```

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/utils/vis/annotations.py#L32

change to
`            cv2.putText(img, "{:.2}".format(score), (x + 2, y + 8), font, 0.3, colors[cls], 1, 0)`

**Comment by GeoffreyChen777** [comment]
@SSSSamZhu Really thanks for your finding!
