### ISSUE TITLE
eval报错

### ISSUE THREAD

**Issue by Bynow76** [ouc-ocean-group/RRNet#2]
eval执行总是报'Dataloader' object is not iterable, 又及为何eval时还是读取了预训练模型和train的数据呢，请问具体怎么操作，不甚感激

**Comment by 48694042** [comment]
作者您好
我这边进行eval的时候显示FileNotFoundError: [Errno 2] No such file or directory: './log/TwoStageNet/ckp-89999.pth'
请问这个缺少的文件我应当如何找到？

**Comment by GeoffreyChen777** [comment]
> 作者您好 我这边进行eval的时候显示FileNotFoundError: [Errno 2] No such file or directory: './log/TwoStageNet/ckp-89999.pth' 请问这个缺少的文件我应当如何找到？

这是你训练保存模型的路径，你可以在这里改成你的路径
https://github.com/ouc-ocean-group/RRNet/blob/353058ec642738bf6956f5fd56501075f2571894/configs/rrnet_config.py#L58

**Comment by 48694042** [comment]
请问应当改哪一个？是将ckp-89999.pth改掉吗？

**Comment by GeoffreyChen777** [comment]
> 请问应当改哪一个？是将ckp-89999.pth改掉吗？

你checkpoint存在哪就改成什么。

**Comment by 48694042** [comment]
抱歉，请问如何寻找checkpoint的位置，还有是将ckp-89999.pth改成checkpoint存放的位置吗？

**Comment by GeoffreyChen777** [comment]
> 抱歉，请问如何寻找checkpoint的位置，还有是将ckp-89999.pth改成checkpoint存放的位置吗？

抱歉这个问题无法帮助到你,我们的默认config原始代码的存放路径就是在`./log/TwoStageNet/`。没有问题。

你训练的模型，理论上只有你自己知道自己的checkpoint在什么地方。

如果你看不懂这个地方怎么调整，建议你找周围的熟悉python的朋友帮助你，我们这边无法帮助你解决这个问题。

**Comment by 48694042** [comment]
好的，非常感谢

**Comment by 48694042** [comment]
我碰到了和issue2同样的问题，但是现在您对上述问题的作答现在已经不可见，可以麻烦您再教教我如何解决
eval执行总是报错'Dataloader' object is not iterable的问题吗？

**Comment by blackcatrecycler** [comment]
@48694042 应该是你的数据集存放的问题，建议对照下config文件里的地址

**Comment by 48694042** [comment]
你好，想询问下rrnet-config.py和test-config.py中的参数设置问题。
1）两个config文件中config.log_prefix中‘TwoStageNet'和‘centernetkl’有什么区别？
2）config.data_root下需要重新划分train、val吗？比如config.data_root='./data/DronesDet'改成'./data/DronesDet/val'
3)   eval执行总是报'Dataloader' object is not iterable, 在rrnrt_operator.py中 for data in selt.validation_lodaer()处报错

**Comment by 48694042** [comment]
具体问题如下：
Start generating Txt file ...
=> Use GPU: 0
3333333333
<datasets.drones_det.DronesDET object at 0x7f82c8199e10>
444444444
./data/DronesDET
5555555555
<datasets.dataloader.Dataloader object at 0x7f82c820e828>
1111111111
<datasets.dataloader.Dataloader object at 0x7f82c815ac50>
22222222
<datasets.dataloader.Dataloader object at 0x7f82c820e828>
----------
./log/TwoStageNet/ckp-89999.pth
8888888888888888
405
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/run01/scv6608/RRNet-master/operators/distributed_wrapper.py", line 69, in dist_evaluation_process
    operator.evaluation_process()
  File "/data/run01/scv6608/RRNet-master/operators/rrnet_operator.py", line 259, in evaluation_process
    for data in self.validation_loader:
TypeError: 'Dataloader' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 26, in _wrap
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 62702) is killed by signal: Terminated. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/multiprocessing/process.py", line 274, in _bootstrap
    traceback.print_exc()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/traceback.py", line 364, in extract
    f.line
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/traceback.py", line 286, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/tokenize.py", line 454, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/tokenize.py", line 423, in detect_encoding
    first = read_or_stop()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/tokenize.py", line 381, in read_or_stop
    return readline()
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 62692) is killed by signal: Terminated. 
Traceback (most recent call last):
  File "eval.py", line 13, in <module>
    dis_operator.eval()
  File "/data/run01/scv6608/RRNet-master/operators/distributed_wrapper.py", line 61, in eval
    args=(self.cfg.Distributed.ngpus_per_node, self.cfg))
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/home/scv6608/.conda/envs/scz0829_torch11/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/run01/scv6608/RRNet-master/operators/distributed_wrapper.py", line 69, in dist_evaluation_process
    operator.evaluation_process()
  File "/data/run01/scv6608/RRNet-master/operators/rrnet_operator.py", line 259, in evaluation_process
    for data in self.validation_loader:
TypeError: 'Dataloader' object is not iterable

**Comment by 48694042** [comment]
4）rrnet-config.py中，Config.num_classes=10,我需要训练的种类数量为7，我将其改成7，报错
RuntimeError: The size of tensor a (7) must match the size of tensor b (10) at non-singleton dimension 1
为什么会出现这个问题？

**Comment by GeoffreyChen777** [comment]
@48694042 

1） 你并不需要关心 test_config，如果你在用RRNet，这个文件对你来说完全无用。无论测试还是训练，都是使用的rrnet的config。而不是这个。
2）配置文件并不需要改，因为在这里自动添加了两个split的路径：
https://github.com/ouc-ocean-group/RRNet/blob/353058ec642738bf6956f5fd56501075f2571894/datasets/drones_det.py#L18
3）这可能是一个Bug，你可以把这个地方的 _Dataloader 去掉，只保留Dataloader：

https://github.com/ouc-ocean-group/RRNet/blob/353058ec642738bf6956f5fd56501075f2571894/datasets/__init__.py#L30

4）这个的报错点在什么地方？
