### ISSUE TITLE
运行脚本后有报错，请帮忙看看

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [ouc-ocean-group/RRNet#7]
我创建好虚拟环境后，其中pytorch版本是1.1.0 ，data里面的数据集是demo，脚本位于RRNet-master目录里面，脚本内容如下：
```
#!/bin/bash
module load anaconda/2020.11
source activate scz0829
export PYTHONUNBUFFERED=1
python ./train.py
```

用来1个GPU来跑，然后有如下报错，请帮忙看看是什么问题导致的呢？

=> Use GPU: 0
Traceback (most recent call last):
  File "./train.py", line 8, in <module>
    dis_operator.train()
  File "/data/run01/scv6002/zhou/RRNet-master/operators/distributed_wrapper.py", line 53, in train
    args=(self.cfg.Distributed.ngpus_per_node, self.cfg))
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/run01/scv6002/zhou/RRNet-master/operators/distributed_wrapper.py", line 64, in dist_training_process
    operator = self.init_operator(gpu, ngpus_per_node, cfg)
  File "/data/run01/scv6002/zhou/RRNet-master/operators/distributed_wrapper.py", line 45, in init_operator
    return self.operator_class(cfg)
  File "/data/run01/scv6002/zhou/RRNet-master/operators/rrnet_operator.py", line 26, in __init__
    model = RRNet(cfg).cuda(cfg.Distributed.gpu_id)
  File "/data/run01/scv6002/zhou/RRNet-master/models/rrnet.py", line 19, in __init__
    self.backbone = get_backbone(cfg.Model.backbone, num_stacks=self.num_stacks)
  File "/data/run01/scv6002/zhou/RRNet-master/utils/model_tools.py", line 25, in get_backbone
    return hourglass_net(num_stacks=num_stacks)
  File "/data/run01/scv6002/zhou/RRNet-master/backbones/hourglass.py", line 209, in hourglass_net
    model.load_state_dict(torch.load('./hourglass.pth'), strict=False)
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
@GeoffreyChen777 @lqxisok

**Comment by GeoffreyChen777** [comment]
@zhoujingyu13687306871 你好，该报错显示是在载入预训练backbone模型的时候出现的问题，不属于本模型的问题。

你可以通过新建一个python 文件，然后

```
import torch

torch.load("./hourglass.pth")
```

这样进行调试，直到无报错。有关报错请联系对应的包作者解决，不属于本模型的范畴。

谢谢。

**Comment by 48694042** [comment]
@GeoffreyChen777 您好，抱歉打扰您一下，我按照您说的新建了那个python文件，然后报错的内容如下：
File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
可以麻烦您指点一二吗？

**Comment by GeoffreyChen777** [comment]
> @GeoffreyChen777 您好，抱歉打扰您一下，我按照您说的新建了那个python文件，然后报错的内容如下： File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 387, in load return _load(f, map_location, pickle_module, **pickle_load_args) File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, '\x0a'. 可以麻烦您指点一二吗？

这报错是说载入模型的时候的问题，你需要去你下载`hourglass.pth`的仓库提问。

**Comment by 48694042** [comment]
好的，谢谢

**Comment by 48694042** [comment]
@GeoffreyChen777 抱歉打扰您
请问您的代码包中annotation中的.txt文件的格式是什么？每一列数字的含义是什么？dataset文件下脚本的作用是什么？

**Comment by GeoffreyChen777** [comment]
@48694042 

annotation 含义请看 http://aiskyeye.com/ 我们使用的就是这个比赛的数据集。
dataset相关脚本就是在加载数据集以及augmentation
