### ISSUE TITLE
torch版本问题

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [ouc-ocean-group/RRNet#8]
您好！我这边按照之前您提出的建议跑通了hourglass.pth ，但是提交到集群计算节点上在GPU加持情况有报错，
=> Use GPU: 0
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    dis_operator.train()
  File "/data/run01/scv6002/zhou/RRNet-master/operators/distributed_wrapper.py", line 53, in train
    args=(self.cfg.Distributed.ngpus_per_node, self.cfg))
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/run01/scv6002/zhou/RRNet-master/operators/distributed_wrapper.py", line 64, in dist_training_process
    operator = self.init_operator(gpu, ngpus_per_node, cfg)
  File "/data/run01/scv6002/zhou/RRNet-master/operators/distributed_wrapper.py", line 45, in init_operator
    return self.operator_class(cfg)
  File "/data/run01/scv6002/zhou/RRNet-master/operators/rrnet_operator.py", line 26, in __init__
    model = RRNet(cfg).cuda(cfg.Distributed.gpu_id)
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: unknown error

脚本内容
#!/bin/bash
module load anaconda/2020.11
source activate scz0829
export PYTHONUNBUFFERED=1
module load cuda/10.1
python3  train.py

pytorch版本1.1.0，cuda版本10.0 python版本3.7

@GeoffreyChen777

**Comment by GeoffreyChen777** [comment]
@zhoujingyu13687306871

你好，关于在你们集群的运行问题，我们无法解决。仓库代码在我们自己机器测试没有问题。抱歉。
